groups:
  - name: compute
    rules:
      # Compute requests
      - record: fastly_service:compute_requests
        expr: sum(rate(fastly_rt_compute_requests_total[120s])) by (service_id,service_name)
      # Compute errors
      - record: fastly_service:compute_errors
        expr: sum(rate(fastly_rt_compute_guest_errors_total[120s])) by (service_id,service_name)
      # Compute resource limits exceeded
      - record: fastly_service:compute_resource_limit_exceeded
        expr: sum(rate(fastly_rt_compute_resource_limit_exceeded_total[120s])) by (service_id,service_name)
