{
 "title": "Fastly Top Origins",
 "tags": [
  "fastly",
  "origin-inspector"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "origin",
    "label": "Origin",
    "query": {
     "query": "label_values(fastly_origin_responses_total, origin)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(fastly_origin_responses_total, service_name)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(fastly_origin_responses_total, service_id)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(fastly_origin_responses_total, datacenter)"
    }
   },
   {
    "name": "rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "top_origin_id_requests_total",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_errors_total",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{status_group=\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_body_size_total",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_resp_body_bytes_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_error_per_request",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{status_group=\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin) / max(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))"
    }
   },
   {
    "name": "top_origin_id_impaired",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{status_group=\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin) / max(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin) ))"
    }
   },
   {
    "name": "top_origin_id_status_group_total_4xx",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_status_group_total_5xx",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_4xx_per_request",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[${__range_s}s])) by (origin) / max(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_5xx_per_request",
    "query": {
     "query": "query_result(topk(10, max(rate(fastly_origin_status_group_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[${__range_s}s])) by (origin) / max(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (origin)))\n"
    }
   },
   {
    "name": "top_origin_id_origin_latency_p99",
    "query": {
     "query": "query_result(topk(10, histogram_quantile(0.99,sum(rate(fastly_origin_latency_seconds_bucket{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[${__range_s}s])) by (le,origin))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ACTIVELY USED ORIGINS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}) by (origin))",
     "legendFormat": "Origins"
    }
   ]
  },
  {
   "title": "SUMMARY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "REQUESTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_origin_responses_total{origin=~\"$top_origin_id_requests_total\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "BANDWIDTH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8 * sum(rate(fastly_origin_resp_body_bytes_total{origin=~\"$top_origin_id_body_size_total\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_status_group_total_4xx\", status_group=~\"4xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_status_group_total_5xx\", status_group=~\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
     "legendFormat": "{{origin}} "
    }
   ]
  },
  {
   "title": "ORIGIN LATENCY - P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(fastly_origin_latency_seconds_bucket{origin=~\"$top_origin_id_origin_latency_p99\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (le,origin,service_id,service_name))",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "4XX IMPAIRED",
     "type": "graph",
     "description": "4XX per REQUESTS by 4XX",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_4xx_per_request\", status_group=~\"4xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
       "legendFormat": "{{origin}}"
      }
     ]
    },
    {
     "title": "5XX IMPAIRED",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_5xx_per_request\", status_group=~\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin,service_id,service_name)",
       "legendFormat": "{{origin}}"
      }
     ]
    },
    {
     "title": "4XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_4xx_per_request\", status_group=\"4xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (service_name,service_id) / sum(rate(fastly_origin_responses_total{origin=~\"$top_origin_id_4xx_per_request\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (service_name,service_id)",
       "legendFormat": "{{origin}}"
      }
     ]
    },
    {
     "title": "5XX per REQUEST",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{origin=~\"$top_origin_id_5xx_per_request\", status_group=\"5xx\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (service_name,service_id) / sum(rate(fastly_origin_responses_total{origin=~\"$top_origin_id_5xx_per_request\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (service_name,service_id)",
       "legendFormat": "{{origin}}"
      }
     ]
    },
    {
     "title": "DEAD ",
     "type": "graph",
     "description": "ERRORS >= REQUESTS, by ERRORS",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{status_group=\"5xx\", origin=~\"$top_origin_id_error_per_request\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin, service_id, service_name) \n",
       "legendFormat": "{{origin}}"
      }
     ]
    },
    {
     "title": "IMPAIRED",
     "type": "graph",
     "description": "REQUESTS > ERRORS, by ERRORS / REQUESTS",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fastly_origin_status_group_total{status_group=\"5xx\", origin=~\"$top_origin_id_impaired\", origin=~\"$origin\", service_name=~\"$service_name\", datacenter=~\"$datacenter\"}[$rate])) by (origin, service_id, service_name) ",
       "legendFormat": "{{origin}}"
      }
     ]
    }
   ]
  },
  { "title": "SOURCE AND STATUS DETAIL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "REQUESTS BY SOURCE",
   "type": "timeseries",
   "description": "Origin Inspector labels every metric with source: delivery, compute or waf, identifying which part of the Fastly platform made the origin request. Nothing in this repo used that label before.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_origin_responses_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "ORIGIN STATUS CODES",
   "type": "timeseries",
   "description": "Individual status codes. The 4XX and 5XX panels above group by status_group, so they cannot distinguish a 503 from a 502.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(fastly_origin_status_code_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (status_code))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "ORIGIN RESPONSE BYTES BY SOURCE",
   "type": "timeseries",
   "description": "Header bytes read 0 for source=compute and source=waf on every exporter release up to v10.3.0: pkg/origin/process.go adds those two sources' header bytes to RespBodyBytesTotal instead, so the header counter stays empty and the body counter is inflated. Only source=delivery is correct here until that is fixed upstream.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_origin_resp_body_bytes_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (source)",
     "legendFormat": "body {{source}}"
    },
    {
     "expr": "sum(rate(fastly_origin_resp_header_bytes_total{origin=~\"$origin\", service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) by (source)",
     "legendFormat": "header {{source}}"
    }
   ]
  }
 ]
}